name : Manual tests

on :
  workflow_dispatch: 
    inputs:
      number:
        description: number in input
        required: true
        type: number
env :
  name : wafae
  surname : fifette
    
        

jobs:
  RunOnlyIfBiggerThanseven: 
    runs-on: ubuntu-latest
    if: inputs.number >= 7
    env:
        colour : black
        shape: circle
    
    steps:
      - name : show the number
        run : echo "the number is ${{inputs.number}}"

      - name : variables
        env :
          dotter : lina
          sons : majdKamil
        run : echo "${{toJson(env)}}"

  BuildInLinuxAndWindows:
    strategy:
      matrix:
        os : [ubuntu-latest, windows-latest]
        dotnet-version : ['8.0.x', '9.0.x', '10.0.x']
    runs-on: ${{ matrix.os }}

    steps:
      - name : checkout
        uses : actions/checkout@v7
        
      - name : setup
        uses : actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name : build
        run : dotnet build
      
      
       
    
    

    
    
